- src/main/java/dgu/sw/global/config/SecurityConfig.java
- src/main/java/dgu/sw/global/config/SwaggerConfig.java
- src/main/java/dgu/sw/global/config/WebConfig.java
- #3 
<br>
- Swagger
- Webconfig
- SecurityConfig
<br>
-
> [Feature] #3 - Config 설정

- src/main/java/dgu/sw/global/ApiResponse.java
- src/main/java/dgu/sw/global/BaseCode.java
- src/main/java/dgu/sw/global/BaseEntity.java
- src/main/java/dgu/sw/global/BaseErrorCode.java
- src/main/java/dgu/sw/global/ErrorReasonDTO.java
- src/main/java/dgu/sw/global/ReasonDTO.java
- src/main/java/dgu/sw/global/RootController.java
- src/main/java/dgu/sw/global/config/SecurityConfig.java
- src/main/java/dgu/sw/global/config/SwaggerConfig.java
- src/main/java/dgu/sw/global/config/WebConfig.java
- src/main/java/dgu/sw/global/status/ErrorStatus.java
- src/main/java/dgu/sw/global/status/SuccessStatus.java
- #5 
<br>
- Response 형식 통일
<br>
-
> [Feature] #5 - Base Code 세팅

- .github/workflows/main.yml
- Dockerfile
- #7 
<br>
- main.yml 생성
- Dockerfile 작성
<br>
-
> [Feature] #7 - CI/CD 준비

- src/main/java/dgu/sw/domain/business/entity/Business.java
- src/main/java/dgu/sw/domain/business/entity/BusinessImage.java
- src/main/java/dgu/sw/domain/manner/entity/FavoriteManner.java
- src/main/java/dgu/sw/domain/manner/entity/Manner.java
- src/main/java/dgu/sw/domain/quiz/entity/Quiz.java
- src/main/java/dgu/sw/domain/quiz/entity/QuizReviewList.java
- src/main/java/dgu/sw/domain/quiz/entity/UserQuiz.java
- src/main/java/dgu/sw/domain/user/entity/User.java
- src/main/java/dgu/sw/domain/voca/entity/FavoriteVoca.java
- src/main/java/dgu/sw/domain/voca/entity/Voca.java
- #9 
<br>
- ERD 생성 및 매핑
<br>
-
> [Feature] #9 - ERD 생성 및 매핑

- .github/workflows/main.yml
- build.gradle
- src/main/java/dgu/sw/domain/business/entity/Business.java
- src/main/java/dgu/sw/domain/manner/entity/Manner.java
- src/main/java/dgu/sw/domain/quiz/entity/Quiz.java
- src/main/java/dgu/sw/domain/quiz/repository/QuizRepository.java
- src/main/java/dgu/sw/domain/quiz/repository/UserQuizRepository.java
- src/main/java/dgu/sw/domain/user/controller/UserController.java
- src/main/java/dgu/sw/domain/user/converter/UserConverter.java
- src/main/java/dgu/sw/domain/user/dto/UserDTO.java
- src/main/java/dgu/sw/domain/user/repository/UserRepository.java
- src/main/java/dgu/sw/domain/user/service/UserService.java
- src/main/java/dgu/sw/domain/user/service/UserServiceImpl.java
- src/main/java/dgu/sw/global/config/SecurityConfig.java
- src/main/java/dgu/sw/global/config/filter/JwtAuthenticationFilter.java
- src/main/java/dgu/sw/global/config/redis/Redis.java
- src/main/java/dgu/sw/global/config/redis/RedisConfig.java
- src/main/java/dgu/sw/global/config/redis/RedisUtil.java
- src/main/java/dgu/sw/global/config/util/JWTUtil.java
- src/main/java/dgu/sw/global/config/util/ResponseUtil.java
- src/main/resources/application.yml
- #18 
<br>
- JWT 인증
- redis 사용
<br>
-
> [Feature] #18 - 회원가입, 로그인 API 구현

- src/main/java/dgu/sw/domain/quiz/service/QuizServiceImpl.java
- src/main/java/dgu/sw/global/exception/ExceptionAdvice.java
- src/main/java/dgu/sw/global/exception/GeneralException.java
- src/main/java/dgu/sw/global/exception/QuizException.java
- src/main/java/dgu/sw/global/status/ErrorStatus.java
- #17 
<br>
- QuizException 설정
<br>
-
> [Feature] #17 - 퀴즈 관련 ERROR status 반환

- src/main/java/dgu/sw/domain/user/service/UserServiceImpl.java
- src/main/java/dgu/sw/global/exception/UserException.java
- src/main/java/dgu/sw/global/status/ErrorStatus.java
- #23 
<br>
- UserException 추가
<br>
-
> [Refactor] #23 - User 관련 ERROR 처리

- src/main/java/dgu/sw/global/config/WebConfig.java
- #27 
<br>
- react native 포트번호 추가 (8081)
<br>
-
> [Fix] #27 - Cors 문제 해결

- src/main/java/dgu/sw/domain/quiz/converter/QuizConverter.java
- src/main/java/dgu/sw/domain/quiz/dto/QuizDTO.java
- src/main/java/dgu/sw/domain/quiz/service/QuizServiceImpl.java
- src/main/java/dgu/sw/global/status/ErrorStatus.java
- #34 
<br>
- 퀴즈 푼 후 복습리스트 추가 기능 수정
<br>
-
> [Refactor] #34 - 퀴즈 푼 후 복습리스트 추가 기능 수정

- src/main/java/dgu/sw/domain/voca/controller/VocaController.java
- src/main/java/dgu/sw/domain/voca/converter/VocaConverter.java
- src/main/java/dgu/sw/domain/voca/dto/VocaDTO.java
- src/main/java/dgu/sw/domain/voca/service/VocaService.java
- src/main/java/dgu/sw/domain/voca/service/VocaServiceImpl.java
- #36 
<br>
- 업무 용어 즐겨찾기 여부 반환 추가
<br>
-
> [Refactor] #36 - 업무 용어 즐겨찾기 여부 반환 추가

- src/main/java/dgu/sw/domain/voca/controller/VocaController.java
- src/main/java/dgu/sw/domain/voca/service/VocaService.java
- src/main/java/dgu/sw/domain/voca/service/VocaServiceImpl.java
- src/main/java/dgu/sw/global/config/SecurityConfig.java
- #36 
<br>
- 업무 용어 Converter 수정
<br>
-
> [Fix] #36 - 업무 용어 Converter 수정

- src/main/java/dgu/sw/domain/quiz/converter/QuizConverter.java
- src/main/java/dgu/sw/domain/quiz/dto/QuizDTO.java
- src/main/java/dgu/sw/domain/quiz/service/QuizServiceImpl.java
- #39 
<br>
- 퀴즈 상세 조회 시 isSolved 추가
<br>
-
> [Refactor] #39 - 퀴즈 상세 조회 시 isSolved 추가

- src/main/java/dgu/sw/domain/quiz/converter/QuizConverter.java
- src/main/java/dgu/sw/domain/quiz/dto/QuizDTO.java
- src/main/java/dgu/sw/domain/quiz/service/QuizServiceImpl.java
- #41 
<br>
- 퀴즈 상세 조회 시 inReviewList 추가
<br>
-
> [Refactor] #41 - 퀴즈 상세 조회 시 inReviewList 추가

- src/main/java/dgu/sw/domain/quiz/service/QuizServiceImpl.java
- #44 
<br>
- 퀴즈 목록 조회 시 isInReviewList가 무조건 false로 반환되는 문제 해결
<br>
-
> [Bug] #44 - 퀴즈 목록 조회 시 isInReviewList 반환 수정

- src/main/java/dgu/sw/domain/manner/controller/MannerController.java
- src/main/java/dgu/sw/domain/manner/converter/MannerConverter.java
- src/main/java/dgu/sw/domain/manner/dto/MannerDTO.java
- src/main/java/dgu/sw/domain/manner/service/MannerService.java
- src/main/java/dgu/sw/domain/manner/service/MannerServiceImpl.java
- #43
<br>
- 매너 리스트, 디테일에 즐겨찾기 여부 추가
<br>
-
> [Refactor] #43 -매너 설명서 API 즐겨찾기 여부 추가

- src/main/java/dgu/sw/domain/quiz/controller/QuizController.java
- src/main/java/dgu/sw/domain/quiz/converter/QuizConverter.java
- src/main/java/dgu/sw/domain/quiz/dto/QuizDTO.java
- src/main/java/dgu/sw/domain/quiz/service/QuizService.java
- src/main/java/dgu/sw/domain/quiz/service/QuizServiceImpl.java
- #47 
<br>
- 복습 리스트 조회 시 correct 추가
<br>
-
> [Refactor] #47 - 복습 리스트 조회 시 correct 추가

- src/main/java/dgu/sw/domain/quiz/converter/QuizConverter.java
- src/main/java/dgu/sw/domain/quiz/service/QuizServiceImpl.java
- #51 
<br>
- 모든 퀴즈 첫번째 문제 lock 해제
<br>
-
> [Refactor] #51 - 모든 퀴즈 첫번째 문제 lock 해제

- src/main/java/dgu/sw/domain/user/controller/UserController.java
- src/main/java/dgu/sw/domain/user/dto/UserDTO.java
- src/main/java/dgu/sw/domain/user/service/UserService.java
- src/main/java/dgu/sw/domain/user/service/UserServiceImpl.java
- #55 
<br>
- 이메일 중복 여부 확인 API 구현
<br>
-
> [Feature] #55 - 이메일 중복 여부 확인 API 구현

- Dockerfile
- src/main/java/dgu/sw/domain/trend/service/TrendService.java
- 이슈 번호
<br>
- 구현 내용 1
- 구현 내용 2
<br>
-
> [Bug] #57 - 트렌드 API 로드 시간 줄임

- src/main/java/dgu/sw/domain/user/controller/UserController.java
- src/main/java/dgu/sw/domain/user/converter/UserConverter.java
- src/main/java/dgu/sw/domain/user/dto/UserDTO.java
- src/main/java/dgu/sw/domain/user/service/UserService.java
- src/main/java/dgu/sw/domain/user/service/UserServiceImpl.java
- src/main/java/dgu/sw/global/config/filter/JwtAuthenticationFilter.java
- src/main/java/dgu/sw/global/config/redis/RedisUtil.java
- src/main/java/dgu/sw/global/status/ErrorStatus.java
- #65 
<br>
- 로그인 성공 시 Response Body에 토큰을 포함하여 클라이언트로 전달
- Access Token 만료 시 Refresh Token으로 갱신 요청
- Refresh Token 유효성 검사 후 new token 발급
<br>
- 서버에서 쿠키 설정, 삭제 등을 처리할 필요가 없어지고, 클라이언트는 토큰을 별도로 추출할 필요가 없어짐.
- 포항항 ~
> [Refactor] #65 - JWT 토큰 Redis 저장 및 Response Body 반환 방식으로 수정

- src/main/java/dgu/sw/domain/manner/converter/MannerConverter.java
- src/main/java/dgu/sw/domain/manner/dto/MannerDTO.java
- #74 
<br>
- 비즈니스 매너 설명서 contentPreview를 전체 content로 변경
<br>
-
> [Refactor] #74 - 비즈니스 매너 설명서 contentPreview를 전체 content로 변경

- src/main/java/dgu/sw/domain/manner/controller/MannerController.java
- src/main/java/dgu/sw/domain/manner/service/MannerService.java
- src/main/java/dgu/sw/domain/manner/service/MannerServiceImpl.java
- src/main/java/dgu/sw/domain/quiz/controller/QuizController.java
- src/main/java/dgu/sw/domain/quiz/service/QuizService.java
- src/main/java/dgu/sw/domain/quiz/service/QuizServiceImpl.java
- #76 
<br>
- 기존에는 요청 파라미터에 String이 들어갔으나 인코딩 문제가 발생할 수 있으므로 int로 수정
<br>
-
> [Refactor] #76 - category 파라미터 String에서 int로 수정

- src/main/java/dgu/sw/domain/manner/controller/MannerController.java
- src/main/java/dgu/sw/domain/manner/service/MannerService.java
- src/main/java/dgu/sw/domain/manner/service/MannerServiceImpl.java
- #79 
<br>
- 매너 설명서의 모든 카테고리를 반환하는 getCategories() 제거
<br>
-
> [Fix] #79 - 불필요한 manner 관련 API 제거

- src/main/java/dgu/sw/domain/quiz/repository/QuizRepository.java
- src/main/java/dgu/sw/domain/quiz/service/QuizServiceImpl.java
- #97 
<br>
- 특정 카테고리 내에서 이전 퀴즈를 풀지 않았을 경우 다음 퀴즈를 풀 수 없도록 수정
<br>
-
> [Refactor] #97 - 퀴즈 순차 진행 로직 추가 (이전 퀴즈 풀었는지 확인)

- src/main/java/dgu/sw/global/status/ErrorStatus.java
- #108 
- 
<br>
- ErrorStatus에 있는 인증코드 관련 에러 중복 제거
<br>
- so easy
> [Bug] #108 - 인증코드 관련 에러 중복 제거

- src/main/java/dgu/sw/domain/user/service/UserServiceImpl.java
- src/main/java/dgu/sw/global/config/util/EmailService.java
- #110 
<br>
- HTML 이메일 전송 지원 (MimeMessage 사용)
- 비밀번호 재설정용 인증코드를 HTML 형식으로 발송
- 이메일 템플릿에 신뢰감 있는 디자인 적용 및 유효시간 안내 추가
<br>
-
> [Refactor] #110 - 비밀번호 재설정용 인증코드 메일을 HTML 형식으로 발송

- .github/workflows/gradle.yml
- .gitignore
- src/main/resources/application.yml
- 이슈 번호
<br>
- github action ci/cd yaml 파일 추가
<br>
-
> Seungwoo deploy 1

- src/main/java/dgu/sw/domain/user/controller/UserController.java
- src/main/java/dgu/sw/domain/user/converter/UserConverter.java
- src/main/java/dgu/sw/domain/user/dto/UserDTO.java
- src/main/java/dgu/sw/domain/user/service/UserService.java
- src/main/java/dgu/sw/domain/user/service/UserServiceImpl.java
- #116 
<br>
- MyPageResponse DTO 생성
- nickname, email, joinDate 포함
- UserConverter.toMyPageResponse(User) 메서드 추가
- UserService 및 UserServiceImpl에 getMyPage(String userId) 구현
- 인증된 사용자 정보 (Authentication.getName()) 기반 조회
<br>
-
> [Feature] #116 - 마이페이지 조회 API 구현

- .github/workflows/gradle.yml
- 이슈 번호
<br>
컨테이너 이름이 중복되는 오류 수정
<br>
-
> 컨테이너 이름이 중복되는 오류 수정

- src/main/java/dgu/sw/domain/auth/controller/AuthController.java
- src/main/java/dgu/sw/domain/auth/service/AuthService.java
- src/main/java/dgu/sw/domain/auth/service/AuthServiceImpl.java
- src/main/java/dgu/sw/global/security/OAuthUtil.java
- src/main/resources/application.yml
- #90 
<br>
- 구글 소셜 로그인 기능 구현
- 서하은님 소셜 로그인 코드 기반 구현
<br>
-
> [Feature] #90 - 구글 소셜 로그인 기능 구현

- src/main/java/dgu/sw/global/config/redis/RedisConfig.java
- src/main/resources/application.yml
- #129 
<br>
- REDIS_TLS 환경변수 추가
- RedisConfig 파일에 ssl 설정 코드 추가
<br>
-
> [Refactor] #129 Redis 환경 변수 REDIS_TLS 추가 및 RedisConfig에 반영

- src/main/resources/application.yml
- #131 
<br>
- application.yml 파일 oauth 들여쓰기 이슈로 환경변수 인식 못하는 것 수정
<br>
-
> [Fix] #131 - application.yml 버그 수정

- src/main/java/dgu/sw/domain/user/controller/UserController.java
- src/main/java/dgu/sw/domain/user/dto/UserDTO.java
- src/main/java/dgu/sw/domain/user/service/UserService.java
- src/main/java/dgu/sw/domain/user/service/UserServiceImpl.java
- src/main/java/dgu/sw/global/status/ErrorStatus.java
- close #136 
<br>
- 소셜 로그인용 입사일 등록 API 구현
- Update와 비슷한 부분이 있어, Update를 쓴 부분도 있음
<br>
-
> [Feature] #136 - 소셜 로그인용 입사일 등록 API

- src/main/java/dgu/sw/domain/user/converter/UserConverter.java
- src/main/java/dgu/sw/domain/user/dto/UserDTO.java
- #139 
<br>
- 마이페이지 조회 시 프로필 이미지 반환
<br>
-
> [Refactor] #139 - 마이페이지 조회 시 프로필 이미지 반환

- src/main/java/dgu/sw/domain/quiz/dto/QuizDTO.java
- src/main/java/dgu/sw/domain/quiz/service/QuizServiceImpl.java
- #144 
<br>
- DTO에 nickname 추가
<br>
-
> [Refactor] #144 - 퀴즈 메인 페이지 조회 시 사용자 nickname 추가 반환

- src/main/java/dgu/sw/domain/user/service/UserServiceImpl.java
- src/main/java/dgu/sw/global/status/ErrorStatus.java
- close #147 
<br>
- 소셜 로그인의 경우 비밀번호 변경 불가능하도록 처리
<br>
> [Refactor] #147 - 소셜 로그인의 경우 비밀번호 변경 불가능하도록 처리

- src/main/java/dgu/sw/global/config/SecurityConfig.java
- src/main/java/dgu/sw/global/security/JwtAuthenticationFilter.java
- src/main/java/dgu/sw/global/status/ErrorStatus.java
- #149 
<br>
- Redis에서 토큰 조회 후 "BLACKLIST"인 경우 UserException(ErrorStatus.LOGGED_OUT_TOKEN) 예외 처리
-> 🚨 근데 현재 401만 뜨고있음 ...
- 로그아웃된 토큰으로 인증 시도 시 차단됨
<br>
-
> [Bug] #149 - 만료되거나 블랙리스트 등록된 토큰 인증 차단 및 예외 처리

- src/main/java/dgu/sw/domain/manner/converter/MannerConverter.java
- src/main/java/dgu/sw/domain/manner/dto/MannerDTO.java
- close #163 
<br>
- 매너 설명서 일반 리스트 & 즐겨찾기 리스트 변수 통일
- 둘 다 content로 하고, 글자수 자르는 건 프에서 한다고 하니 글자수 제한을 백에서는 없앰
<br>
-
> [Refactor] #163 - 매너 설명서 일반 리스트 & 즐겨찾기 리스트 변수 통일

- src/main/java/dgu/sw/domain/manner/controller/MannerController.java
- src/main/java/dgu/sw/domain/manner/repository/MannerRepository.java
- src/main/java/dgu/sw/domain/manner/service/MannerService.java
- src/main/java/dgu/sw/domain/manner/service/MannerServiceImpl.java
- #159 
<br>
- JPQL @Query 메서드(searchByCategoryAndKeyword)로 category AND (title OR content) 조건 명확히 정의
<br>
-
> [Feature] #159 - 카테고리 내 매너 검색 시 정확한 카테고리 필터링 적용

- src/main/java/dgu/sw/domain/auth/controller/AuthController.java
- src/main/java/dgu/sw/domain/auth/service/AuthService.java
- src/main/java/dgu/sw/domain/auth/service/AuthServiceImpl.java
- src/main/java/dgu/sw/global/security/OAuthUtil.java
- src/main/java/dgu/sw/global/status/ErrorStatus.java
- #158 
<br>
- identityToken 받아서 email 조회
<br>
-
> [Feature] #158 애플 로그인 구현

- build.gradle
- src/main/java/dgu/sw/domain/user/service/UserServiceImpl.java
- src/main/java/dgu/sw/global/security/OAuthUtil.java
- src/main/resources/application.yml
- #169 
<br>
- 회원 탈퇴 시 토큰 해지
<br>
-
> [Feature] #169 - 애플 로그인 회원 탈퇴 API 구현

- src/main/java/dgu/sw/domain/quiz/service/QuizServiceImpl.java
- #173 
<br>
- 카테고리별 퀴즈 매칭이 잘못되어 있었음
- 순서에 맞게 변경 완료
<br>
-
> [Bug] #173 - 카테고리별 퀴즈 매핑 오류 해결

- src/main/java/dgu/sw/domain/quiz/service/QuizServiceImpl.java
- #175 
<br>
- isLocked가 false로 고정되는 문제 해결
- 해당 카테고리의 이전 퀴즈 풀었는지 확인 후 잠금 설정 or 해제
<br>
-
> [Refactor] #175 - Top 5 퀴즈 중 상태에 맞게 잠금(isLocked) 설정

- src/main/java/dgu/sw/SwApplication.java
- src/main/java/dgu/sw/domain/notification/controller/NotificationController.java
- src/main/java/dgu/sw/domain/notification/dto/NotificationResponse.java
- src/main/java/dgu/sw/domain/notification/entity/Notification.java
- src/main/java/dgu/sw/domain/notification/repository/NotificationRepository.java
- src/main/java/dgu/sw/domain/notification/scheduler/NotificationScheduler.java
- src/main/java/dgu/sw/domain/notification/service/NotificationService.java
- src/main/java/dgu/sw/domain/notification/service/NotificationServiceImpl.java
- src/main/java/dgu/sw/domain/user/controller/UserController.java
- src/main/java/dgu/sw/domain/user/dto/UserDTO.java
- src/main/java/dgu/sw/domain/user/entity/User.java
- src/main/java/dgu/sw/domain/user/service/UserService.java
- src/main/java/dgu/sw/domain/user/service/UserServiceImpl.java
- src/main/java/dgu/sw/global/exception/NotificationException.java
- src/main/java/dgu/sw/global/fcm/config/FirebaseInitializer.java
- src/main/java/dgu/sw/global/fcm/dto/FCMNotificationRequest.java
- src/main/java/dgu/sw/global/fcm/service/FCMService.java
- src/main/java/dgu/sw/global/status/ErrorStatus.java
- src/main/resources/application.yml
- #146 
<br>
- 아침 시간대 or 사용자 설정 시간에 → **(백) 현재는 8시 기준으로 설정, 추후 사용자 설정으로 수정 예정**
- `mockTest` 완료일 기준 N일간 미접속 시 알림 → **(백) 현재는 9시 기준으로 설정, 추후 사용자 설정으로 수정 예정**
- 기존 코드로 푸시 잘 됨 → **(백) 백으로 확인했을 때 잘 됨**
<br>
- 프 연동 후 다시 맞춰보기
> [Feature] #146 - 알림 기능 구현

- build.gradle
- #188 
<br>
- firebase 관련 build.gradle을 수정
<br>
> [Refactor] #188 - build.gradle 수정

- .gitignore
- src/main/java/dgu/sw/domain/auth/service/AuthServiceImpl.java
- src/main/java/dgu/sw/domain/quiz/entity/Quiz.java
- src/main/java/dgu/sw/domain/quiz/entity/QuizLevel.java
- src/main/java/dgu/sw/domain/quiz/generator/LevelBasedQuizListGenerator.java
- src/main/java/dgu/sw/domain/quiz/generator/QuizListGenerator.java
- src/main/java/dgu/sw/domain/quiz/generator/RandomQuizListGenerator.java
- src/main/java/dgu/sw/domain/quiz/repository/QuizRepository.java
- src/main/java/dgu/sw/domain/quiz/service/MockTestServiceImpl.java
- src/main/resources/application.yml
- #189 
<br>
- 퀴즈 엔티티에 난이도 컬럼 추가
- 기존 모의고사 생성 방식을 MockTestGenerator 인터페이스로 리팩토링
- LevelBasedTestGenerator 구현 - 난이도 기반 모의고사 구성 클래스
<br>
-
> 모의고사 난이도 조절 기능 추가

- src/main/java/dgu/sw/domain/admin/controller/AdminController.java
- src/main/java/dgu/sw/domain/admin/converter/AdminConverter.java
- src/main/java/dgu/sw/domain/admin/dto/AdminDTO.java
- src/main/java/dgu/sw/domain/admin/service/AdminService.java
- src/main/java/dgu/sw/domain/admin/service/AdminServiceImpl.java
- src/main/java/dgu/sw/domain/manner/entity/Manner.java
- src/main/java/dgu/sw/domain/quiz/entity/Quiz.java
- src/main/java/dgu/sw/domain/voca/entity/Voca.java
- #200 
<br>
- 단어, 퀴즈, 매너 수정 API 구현
- ApiResponse 응답 통일
<br>
-
> [Feature] #200 - 단어, 퀴즈, 매너 수정 API 구현

- src/main/java/dgu/sw/domain/admin/converter/AdminConverter.java
- #206 
<br>
- 관리자 페이지에서 퀴즈 등록 시 퀴즈 레벨 추가 저장
<br>
-
> [Fix] #206 - 퀴즈 레벨 추가 저장

- src/main/java/dgu/sw/domain/admin/converter/AdminConverter.java
- #212 
<br>
- 관리자 페이지에서 피드백 목록 호출 시 NPE 방지
<br>
-
> [Fix] #212 - user != null 여부를 체크하고 null인 경우 email, nickname은 그대로 null 반환

- src/main/resources/application.yml
- #188 
<br>
- application.yml에 관련없는 코드가 커밋된 것을 삭제합니다.
> [Refactor] #188 - 관련 없는 코드 삭제
